export { default as PersonalDetails } from "./PersonalDetails";
export type { PersonalDetailsHandle } from "./PersonalDetails";
export { default as LocationDetails } from "./LocationDetails";
export type { LocationDetailsHandle } from "./LocationDetails";
export { default as GuardianDetails } from "./GuardianDetails";
export { default as EducationDetails } from "./EducationDetails";
export { default as CourseDetails } from "./CourseDetails";
export { default as Documents } from "./Documents";
export { default as FeeHistory } from "./FeeHistory";
export type { ProfileFormData } from "./types";
