export { default as PersonalDetails } from "./PersonalDetails";
export type { StepHandle } from "./PersonalDetails";
export { default as LocationDetails } from "./LocationDetails";
export { default as GuardianDetails } from "./GuardianDetails";
export { default as EducationDetails } from "./EducationDetails";
export { default as CourseDetails } from "./CourseDetails";
export { default as Documents } from "./Documents";
export type { RegisterFormData } from "./types";
export { personalDetailsSchema, personalDetailsFieldNames } from "./schemas";
export type { PersonalDetailsValues } from "./schemas";
